# Generated by Django 5.2.6 on 2025-09-17 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatlog_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatlog',
            name='score',
        ),
        migrations.AddField(
            model_name='chatlog',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='chatlog',
            name='latency',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='model_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='provider',
            field=models.CharField(default='openai', max_length=100),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='response_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='status',
            field=models.CharField(default='success', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='tokens_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
