# Generated by Django 5.2.6 on 2025-09-17 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_remove_chatlog_score_chatlog_cost_chatlog_latency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatlog',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='chatlog',
            name='latency',
        ),
        migrations.AddField(
            model_name='chatlog',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='model_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='response_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='status',
            field=models.CharField(default='success', max_length=50),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='tokens_used',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
