# Generated by Django 5.2.6 on 2025-09-17 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_remove_chatlog_score_chatlog_cost_chatlog_latency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlog',
            name='model_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='provider',
            field=models.CharField(default='openai', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
